name: Daily Reddit Meme

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python daily_reddit_meme_to_discord.py
        env:
          DISCORD_RANDOM_WEBHOOK_URL: ${{ secrets.DISCORD_RANDOM_WEBHOOK_URL }}
